### ISSUE TITLE
loading the venues in -- it shows up blank

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsScreen#1]
Hey friend! Here is what I am getting when loading the venues in -- it shows up blank when i add the title for the venue. 

Is there a way to launch the lesson editor without the title showing up? 
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/65249159/176762770-f74d0281-492c-43e6-aff2-b4cbda2bb3d0.png">

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/LessonsApp/commit/2990f7d3ff7e8613a8ace9c9183931471d4ea9a3
