### ISSUE TITLE
Can't turn off live 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsScreen#2]
It is off they are not live on the website but the button makes them look like they are live 
![image_123927839](https://user-images.githubusercontent.com/65249159/176767635-2c5e9c57-3a52-4341-9dc3-74236219b6e4.JPG)

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/LessonsApp/commit/0ffb2686b12f58aa8b18efbab2c3a9cb23ab97d9
