### ISSUE TITLE
You can’t create a venue for some reason. And you can’t just click the blank space and move forward either. 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsScreen#3]
can’t create a venue for some reason. And you can’t just click the blank space and move forward either.

![image_123927839](https://user-images.githubusercontent.com/65249159/176767915-71f1db93-d557-4c8a-ba2c-ee3d3f34928e.JPG)
 Not home right now.  If you click edit can you give it a name?

Nope. Can’t do anything but co timid to create more blank venues. It does t auto pop the number or retain the number you put in either.

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/LessonsApp/commit/2990f7d3ff7e8613a8ace9c9183931471d4ea9a3
